### ISSUE TITLE
error using unicode commands

### ISSUE THREAD

**Issue by mwhooker** [kennethreitz/envoy#77]
Looks like a problem lexing unicode commands.

This is with current latest envoy as pulled from pip.

```
Python 2.7.10 (default, Jul 14 2015, 19:46:27)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import envoy
>>> r = envoy.run(u'uptime')
>>> r.std_out
''
>>> r.std_err
u'No such file or directory\nTraceback (most recent call last):\n  File "/Users/mwhooker/dev/wercker/devbox/formation/venv/lib/python2.7/site-packages/envoy/core.py", line 214, in run\n    out, err = cmd.run(data, timeout, kill_timeout, env, cwd)\n  File "/Users/mwhooker/dev/wercker/devbox/formation/venv/lib/python2.7/site-packages/envoy/core.py", line 93, in run\n    raise self.exc\nOSError: [Errno 2] No such file or directory\n'
>>> r.__dict__
{'std_err': u'No such file or directory\nTraceback (most recent call last):\n  File "/Users/mwhooker/dev/wercker/devbox/formation/venv/lib/python2.7/site-packages/envoy/core.py", line 214, in run\n    out, err = cmd.run(data, timeout, kill_timeout, env, cwd)\n  File "/Users/mwhooker/dev/wercker/devbox/formation/venv/lib/python2.7/site-packages/envoy/core.py", line 93, in run\n    raise self.exc\nOSError: [Errno 2] No such file or directory\n', 'std_out': '', 'status_code': 127, '_process': <envoy.core.Command object at 0x107fe4390>, 'command': u'e', 'history': [<Response [u]>, <Response [p]>, <Response [t]>, <Response [i]>, <Response [m]>]}
```

**Comment by marcwebbie** [comment]
Hello @mwhooker, Project seems to be abandoned, 😢 

I had thesame issue as you could get it working from master with:

```
pip install -U https://github.com/kennethreitz/envoy/archive/master.zip
```

Thanks

**Comment by tonicbupt** [comment]
@kennethreitz Hello, when will the fixed version be released... I'd really wanna use `pip install envoy` to install this rather than `pip install -U https://github.com/kennethreitz/envoy/archive/master.zip` .....
